
hl.on("hyprland.start", function()
    hl.exec_cmd("kdeconnectd")
end)
hl.on("hyprland.start", function()
    hl.exec_cmd("vicinae server")
end)
hl.on("hyprland.start", function()
    hl.exec_cmd("protonvpn-app")
end)
